<?php
ob_end_clean();
class MYPDF extends TCPDF {
    public function Header() {
        $this->Image(ROOT . 'views' . DS . 'layout' . DS . 'default' . DS . 'img' . DS . 'logo.jpeg', 10, 8, 20, 18, 'JPG', false, 'C', true, 300, '', false, false, false, false, false, false);
        $this->SetFont('times', 'B', 8);
        $this->Cell(20, 10, '', false, true, 'L');
        $this->SetFont('times', 'B', 15);
        $this->Cell(20, 10, '', false, false, 'L');
        $this->Cell(0, 4, APP_NAME, false, true, 'C');
        $this->SetFont('times', 'B', 15);
        $this->Cell(20, 10, '', false, false, 'L');
        $this->Cell(0, 4, 'Caja de Ahorro de la Universidad Politecnica Territorial', false, true, 'C');
        $this->Cell(20, 10, '', false, false, 'L');
        $this->Cell(0, 4, 'del Norte del Tachira Manuela Saenz', false, true, 'C');
        $this->SetFont('times', 'B', 13);
        $this->Cell(20, 10, '', false, false, 'L');
        $this->Cell(0, 4, reporteController::$titulo, false, true, 'L');
        $this->SetFont('times', '', 8);
        $this->Ln();
    }
    
    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('times', 'BI', 8);
        $this->Cell(60, 5, "Fecha de Impresión: ".date("d-m-Y h:i:s A"), false, false, 'C');
        $this->Cell(0, 5, 'Página: '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), false, false, 'R');
    }
}
$this->pdf = new MYPDF('P', 'mm', 'Letter', true, 'UTF-8', false);
$this->pdf->SetMargins(7, 40, 7);
$this->pdf->SetAutoPageBreak(true, 18);
$this->pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
$this->pdf->SetFont('times', '', 10);
$this->pdf->AddPage();
$this->pdf->Ln();
$this->pdf->SetFont('times', 'B', 12);
$this->pdf->Cell(0, 6, 'Datos del Socio', false, true, 'L');
$this->pdf->Ln();
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Cédula', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(40, 6, $view->Cedula($datos['cedula_rif_soc']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(50, 6, 'Apellidos y Nombres', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $datos['apellidos_soc'] . ' ' . $datos['nombres_soc'], true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Teléfonos', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(60, 6, $view->Telefono($datos['telefono_soc']) . ' / ' . $view->Telefono($datos['telefono2_soc']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Departamento', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $datos['nombre_dep'], true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Dirección', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $datos['direccion_soc'], true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Sueldo', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(37, 6, $view->Dinero($datos['sueldo_soc']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Aporte Socio', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(37, 6, $view->Dinero(($datos['aporte_socio_soc'] / 100) * $datos['sueldo_soc']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Aporte Patrono', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $view->Dinero(($datos['aporte_patrono_soc'] / 100) * $datos['sueldo_soc']), true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Banco', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(67, 6, $datos['banco_soc'], true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(37, 6, 'Tipo de Cuenta', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $datos['tipo_cuenta_soc'], true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(40, 6, 'Número de Cuenta', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(94, 6, $datos['numero_cuenta_soc'], true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Estado del Socio', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $datos['estado_soc'], true, true, 'C');
$this->pdf->Ln();
$this->pdf->SetFont('times', 'B', 12);
$this->pdf->Cell(0, 6, 'Datos del Prestamo', false, true, 'L');
$this->pdf->Ln();
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Fecha de Solicitud', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(35, 6, $view->Fecha($datos['fecha_solicitud_pre']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(35, 6, 'Fecha de Aprobacion', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(35, 6, $view->Fecha($datos['fecha_aprobacion_pre']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(35, 6, 'Estado del Prestamo', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $datos['estado_pre'], true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Tipo de Prestamo', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(35, 6, $datos['tipo_prestamo_pre'], true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(35, 6, 'Taza de Interes', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(35, 6, $view->Decimal($datos['interes_pre']) . ' %', true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(35, 6, 'Plazo', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(0, 6, $view->Cantidad($datos['plazo_pre']), true, true, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Monto', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(55, 6, $view->Dinero($datos['monto_pre']), true, false, 'C');
$this->pdf->SetFont('times', 'B', 10);
$this->pdf->Cell(30, 6, 'Pagado', true, false, 'C');
$this->pdf->SetFont('times', '', 10);
$this->pdf->Cell(55, 6, $view->Dinero($datos['total_pagado']), true, true, 'C');
if (isset($cuotas) && count($cuotas)):
    $this->pdf->Ln();
    $this->pdf->SetFont('times', 'B', 12);
    $this->pdf->Cell(0, 6, 'Amortizaciones', false, true, 'L');
    $this->pdf->Ln();
    $this->pdf->SetFont('times', 'B', 10);
    $this->pdf->Cell(15, 6, 'N.C.', true, false, 'C');
    $this->pdf->Cell(30, 6, 'Fecha', true, false, 'C');
    $this->pdf->Cell(32, 6, 'Cuota', true, false, 'C');
    $this->pdf->Cell(32, 6, 'Interes', true, false, 'C');
    $this->pdf->Cell(32, 6, 'Amortizacion', true, false, 'C');
    $this->pdf->Cell(32, 6, 'Capital Vivo', true, false, 'C');
    $this->pdf->Cell(0, 6, 'Estado', true, true, 'C');
    $this->pdf->SetFont('times', '', 9);
    $total_cuota = 0;
    $total_interes = 0;
    $total_amortizacion = 0;
    foreach ($cuotas AS$c) {
        $this->pdf->Cell(15, 6, $view->Cantidad($c['numero_cuo_pre']), true, false, 'C');
        $this->pdf->Cell(30, 6, $view->Fecha($c['fecha_cuo_pre']), true, false, 'C');
        $this->pdf->Cell(32, 6, $view->Dinero($c['cuota_cuo_pre']), true, false, 'C');
        $this->pdf->Cell(32, 6, $view->Dinero($c['interes_cuo_pre']), true, false, 'C');
        $this->pdf->Cell(32, 6, $view->Dinero($c['amortizacion_cuo_pre']), true, false, 'C');
        $this->pdf->Cell(32, 6, $view->Dinero($c['capital_vivo_cuo_pre']), true, false, 'C');
        $this->pdf->Cell(0, 6, $c['estado_cuo_pre'], true, true, 'C');
        $total_cuota = $total_cuota + $c['cuota_cuo_pre'];
        $total_interes = $total_interes + $c['interes_cuo_pre'];
        $total_amortizacion = $total_amortizacion + $c['amortizacion_cuo_pre'];
    }
    $this->pdf->SetFont('times', 'B', 9);
    $this->pdf->Cell(45, 6, 'Totales', true, false, 'C');
    $this->pdf->SetFont('times', '', 9);
    $this->pdf->Cell(32, 6, $view->Dinero($total_cuota), true, false, 'C');
    $this->pdf->Cell(32, 6, $view->Dinero($total_interes), true, false, 'C');
    $this->pdf->Cell(32, 6, $view->Dinero($total_amortizacion), true, true, 'C');
    $this->pdf->Ln();
endif;
if (isset($pagos) && count($pagos)):
    $this->pdf->SetFont('times', 'B', 12);
    $this->pdf->Cell(0, 6, 'Pagos', false, true, 'L');
    $this->pdf->Ln();
    $this->pdf->SetFont('times', 'B', 10);
    $this->pdf->Cell(40, 6, 'Fecha', true, false, 'C');
    $this->pdf->Cell(40, 6, 'Abono Capital', true, false, 'C');
    $this->pdf->Cell(40, 6, 'Abono Intereses', true, false, 'C');
    $this->pdf->Cell(40, 6, 'Monto Total', true, false, 'C');
    $this->pdf->Cell(0, 6, 'Estado', true, true, 'C');
    $this->pdf->SetFont('times', '', 9);
    foreach ($pagos AS$p) {
        $this->pdf->Cell(40, 6, $view->Fecha($p['fecha_pag_pre']), true, false, 'C');
        $this->pdf->Cell(40, 6, $view->Dinero($p['monto_capital_pag_pre']), true, false, 'C');
        $this->pdf->Cell(40, 6, $view->Dinero($p['monto_interes_pag_pre']), true, false, 'C');
        $this->pdf->Cell(40, 6, $view->Dinero($p['monto_total_pag_pre']), true, false, 'C');
        $this->pdf->Cell(0, 6, $p['estado_mov'], true, true, 'C');
    }
endif;
$this->pdf->Output(reporteController::$titulo . ".pdf", 'I');
